[phases.setup]
nixPkgs = [
  "python312Full",
  "pip",
  "gcc",
  "git"
]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "gunicorn app:app"
