[phases.setup]
nixPkgs = ["gcc", "python311", "git"]

[phases.install]
cmds = [
  "python -m venv venv",
  ". venv/bin/activate",
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[phases.start]
cmd = "gunicorn app:app"
